### ISSUE TITLE
Add instructions on how to use split apk installers

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [HitaloSama/VancedMirror#1]
I was gonna add that myself in my repo but i noticed you copied my description( im not rude, infact thank you for crediting me :D ), so my repo is now useless so i thought about posting the instructions here

Split APKs Installer

You can also opt for some split APKs installer like SAI.

Instructions:
1. Go to [Beta](https://github.com/HitaloSama/VancedMirror/tree/main/api%2Fbeta) if you want beta versions or [v1](https://github.com/HitaloSama/VancedMirror/tree/main/api%2Fv1)  if you want the stable(or aka v1 versions)
2. Choose which version you want to install
3. Go to {beta or v1}/apks/{version}/{variant}/
4. Now open the Arch folder and choose your artitecture (if you have a phone, you are most possibly an arm64, if you are using any android fork for pc(ie android x86) then you chooce x86
5. Go back 
6. Choose Language and grab as many languages as you want 
7. And finally go to theme and get **only 1** theme 
8. Open your multiapk installer and select everything you just downloaded
9. Install
10. Now you have Vanced!

**Comment by HitaloM** [comment]
> I was gonna add that myself in my repo but i noticed you copied my description( im not rude, infact thank you for crediting me :D ), so my repo is now useless so i thought about posting the instructions here
> 
> 
> Split APKs Installer
> 
> You can also opt for some split APKs installer like SAI.
> 
> Instructions:
> 1. Go to [Beta](https://github.com/HitaloSama/VancedMirror/tree/main/api%2Fbeta) if you want beta versions or [v1](https://github.com/HitaloSama/VancedMirror/tree/main/api%2Fv1)  if you want the stable(or aka v1 versions)
> 2. Choose which version you want to install
> 3. Go to {beta or v1}/apks/{version}/{variant}/
> 4. Now open the Arch folder and choose your artitecture (if you have a phone, you are most possibly an arm64, if you are using any android fork for pc(ie android x86) then you chooce x86
> 5. Go back 
> 6. Choose Language and grab as many languages as you want 
> 7. And finally go to theme and get **only 1** theme 
> 8. Open your multiapk installer and select everything you just downloaded
> 9. Install
> 10. Now you have Vanced!

Thank you! I'll add those instructions.
